server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; connect-src 'self' https://timecrax.ipb.pt; font-src 'self' data:;" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}
